---
- name: {{ APP_NAME }}
  hosts: all
  remote_user: root
  sudo: yes

  vars:
    app_name: {{ APP_NAME }}
    app_user: "{{app_name}}"
    app_fqdn: "{{app_name}}.fr"
    app_dir: "/usr/local/{{app_name}}"
    log_dir: "{{app_dir}}/log"

    python_virtualenv_dir: "{{app_dir}}/.env"
    python3_enabled: true

    git_remote_url: {{ PROJECT_URL }}
    git_branch: master

    uwsgi_config_dir: "{{app_dir}}/uwsgi"

    nginx_site_availables:
      app: # CHANGE_ME put the name of your application
        - "listen      80"
        - "server_name {{app_fqdn}}"
        - "charset     utf-8"
        - "location ~ /static/ {root {{app_dir}}/www;}"
        - "location / {include uwsgi_params;uwsgi_pass unix:/tmp/uwsgi.sock;}"

    supervisor_process:
      app: # CHANGE_ME put the name of your application
        - "[program:app]"
        - "command={{python_virtualenv_dir}}/bin/uwsgi --ini {{uwsgi_config_dir}}/{{app_name}}.ini"
        - "numprocs=1"
        - "process_name={{app_name}}"
        - "stdout_logfile={{log_dir}}/{{app_name}}.supervisor.log"
        - "loglevel=debug"
        - "redirect_stderr=true"
        - "autostart=true"
        - "autorestart=true"
        - "user={{app_user}}"

    uwsgi_configs:
      app: # CHANGE_ME put the name of your application
        - "[uwsgi]"
        - "chdir = {{app_dir}}"
        - "env = {{python_virtualenv_dir}}"
        - "pythonpath = %(chdir)"
        - "processes = 1"
        - "module = run"
        - "callable = {{app_name}}"
        - "uid = {{app_user}}"
        - "gid = {{app_user}}"
        - "socket = /tmp/{{app_name}}.uwsgi.sock"
        - "chmod-socket = 666"
        - "logto = {{log_dir}}/{{app_name}}.uwsgi.log"

  roles:
    - nginx
    - archivist
    - python-virtualenv
    - mongodb
    - supervisor
    - uwsgi
