---
- name: {{ APP_NAME }}
  hosts: all
  remote_user: root
  sudo: yes

  vars:
    nginx_site_availables:
      default:
        - listen      80
        - server_name {{ APP_FQDN }}
        - charset     utf-8
        - location ~ /static/ {root /var/www;}
        - location / {include uwsgi_params;uwsgi_pass unix:/tmp/uwsgi.sock;}

    app_name: {{ APP_NAME }}

    git_remote_url: {{ PROJECT_URL }}
    git_branch: master

    python_virtualenv_dir: "/usr/local/{{app_name}}/.env"
    python3_enabled: true

  roles:
    - nginx
    - archivist
    - python-virtualenv