---
- name: Git archive application
  local_action: command git archive --format zip --output {{app_name}}.zip --remote={{git_remote_url}} {{git_branch}}
  sudo: no

- name: Create app dir if not exists
  file: path={{ app_dir }} state=directory mode=0755

- name: Unarchive app
  unarchive: src={{app_name}}.zip dest={{ app_dir }}
  
- name: delete archive
  local_action: command rm {{app_name}}.zip
  sudo: no