---
- name: Install packages required by the Django app inside virtualenv
  become_user: "{{ app_user }}"
  pip:
    virtualenv: "{{ python_virtualenv_dir }}"
    requirements: "{{ requirements_file }}"
  tags: [python,virtualenv]

- name: Run Django database migrations
  become_user: "{{ app_user }}"
  django_manage:
    command: migrate
    app_path: "{{ app_dir }}"
    virtualenv: "{{ python_virtualenv_dir }}"
    settings: "{{ django_settings_file }}"
  tags: [django,migrate]

- name: Load Django fixtures
  become_user: "{{ app_user }}"
  django_manage:
    command: loaddata
    fixtures: "{{ django_fixtures }}"
    app_path: "{{ app_dir }}"
    virtualenv: "{{ python_virtualenv_dir }}"
    settings: "{{ django_settings_file }}"
  when: django_fixtures is defined
  tags: [django,loaddata]

- name: Run Django collectstatic
  become_user: "{{ app_user }}"
  django_manage:
    command: collectstatic
    app_path: "{{ app_dir }}"
    virtualenv: "{{ python_virtualenv_dir }}"
    settings: "{{ django_settings_file }}"
  tags: [django,collectstatic]
