---
- name: Install python 27 and python 34
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - python2.7
    - python-setuptools
    - python-pip
    - python-virtualenv
    - python3.4
  tags: [packages,python]

- name: remove virtualenv folder
  file: path={{ python_virtualenv_dir }} state=absent

- name: create python 34 virtualenv
  command: virtualenv -p python3 {{ python_virtualenv_dir }}
  when: python3_enabled

- name: create python 27 virtualenv
  command: virtualenv {{ python_virtualenv_dir }}
  when: not python3_enabled
