---
- name: remove virtualenv folder
  file: path={{ python_virtualenv_dir }} state=absent
  when: python_remove_virtualenv

- include: Debian.yml
  when: ansible_os_family == "Debian"
  tags: [debian,python]

- include: FreeBSD.yml
  when: ansible_os_family == "FreeBSD"
  tags: [freebsd,python]

- name: Change virtual env permissions and ownership to {{ app_user }}
  file: recurse=yes owner={{ app_user }} group={{ app_user }} path={{ python_virtualenv_dir }}